### ISSUE TITLE
Basic tasks

### ISSUE THREAD

**Issue by georgw777** [georgw777/CS5052-Spark#1]
# Part 1: basic
- [x] Store dataset using the methods supported in Spark
- [x] Search user by id, show the number of movies/genre that they have watched
  - [x] Given a list of users, search all movies watched by each user
- [x] Search movie by id/title, show the average rating & the number of users that have watched the movie
- [x] Search genre, show all movies in that genre
  - [x] Given a list of genres, search all movies belonging to each genre
- [x] Search movies by year
- [x] List the top n movies with highest rating, ordered by the rating
- [x] List the top n movies with the highest number of watches, ordered by the number of watches

# Part 2: intermediate
- [x] Find the favourite genre of a given user, or group of users. Consider and justify how you will define ‘favourite’.
- [x] Compare the movie tastes of two users. Consider and justify how you will compare and present the data.

# Part 3: advanced (see #2 & #3 for more)
- [x] Cluster users by movie taste.
- [x] Visualisation and interaction of the data set, using external libraries (see #4)
- [x] Provide movie recommendations, e.g., user x liked movies A, B and C therefore they might like movies X, Y and Z (see #5)
