### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by komodo108** [georgw777/CS5052-Spark#3]
Implement a frontend to interact with the dataset & see visualisations.
Perhaps use [d3.js](http://d3js.org/) to provide for visualisations & [react.js](https://reactjs.org/).

## Task List
- [x] Implement a search bar allowing users to search the dataset by column type (like one of those search bars with a dropdown menu)
- [x] Talk to the backend to get results
- [x] Display them in a sensible way
- [ ] Implement custom views for aggregate data - comparing 2 users, seeing clustering, etc.
